// <auto-generated />
using System;
using McSystems.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace McSystems.DataAccess.Migrations
{
    [DbContext(typeof(McSystemsContext))]
    [Migration("20221225073238_251222LastUpdate")]
    partial class _251222LastUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CustomerReservation", b =>
                {
                    b.Property<int>("CustomersId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationsId")
                        .HasColumnType("int");

                    b.HasKey("CustomersId", "ReservationsId");

                    b.HasIndex("ReservationsId");

                    b.ToTable("CustomerReservation");
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Türkiye"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Amerika"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Arjantin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fransa"
                        },
                        new
                        {
                            Id = 5,
                            Name = "İtalya"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Almanya"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Rusya"
                        },
                        new
                        {
                            Id = 8,
                            Name = "İngiltere"
                        },
                        new
                        {
                            Id = 9,
                            Name = "İsveç"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Danimarka"
                        });
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("varchar(120)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("IdNumber")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte>("Capacity")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte>("Floor")
                        .HasColumnType("tinyint");

                    b.Property<bool>("InMaintenance")
                        .HasColumnType("bit");

                    b.Property<byte>("Number")
                        .HasColumnType("tinyint");

                    b.Property<int>("RoomType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Floor", "Number")
                        .IsUnique();

                    b.ToTable("Room", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = (byte)2,
                            Description = "2 kişilik çift yataklı oda",
                            Floor = (byte)1,
                            InMaintenance = false,
                            Number = (byte)1,
                            RoomType = 2
                        },
                        new
                        {
                            Id = 2,
                            Capacity = (byte)2,
                            Description = "2 kişilik çift yataklı oda",
                            Floor = (byte)1,
                            InMaintenance = false,
                            Number = (byte)2,
                            RoomType = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = (byte)2,
                            Description = "2 kişilik tek yataklı oda",
                            Floor = (byte)1,
                            InMaintenance = false,
                            Number = (byte)3,
                            RoomType = 1
                        },
                        new
                        {
                            Id = 4,
                            Capacity = (byte)4,
                            Description = "2 kişilik 2 adet çift yataklı oda",
                            Floor = (byte)2,
                            InMaintenance = false,
                            Number = (byte)1,
                            RoomType = 10
                        },
                        new
                        {
                            Id = 5,
                            Capacity = (byte)5,
                            Description = "deniz manzaralı 5 kişilik çift yataklı oda",
                            Floor = (byte)2,
                            InMaintenance = false,
                            Number = (byte)2,
                            RoomType = 6
                        },
                        new
                        {
                            Id = 6,
                            Capacity = (byte)6,
                            Description = "çift yataklı aile odası",
                            Floor = (byte)2,
                            InMaintenance = false,
                            Number = (byte)3,
                            RoomType = 9
                        },
                        new
                        {
                            Id = 7,
                            Capacity = (byte)6,
                            Description = "çift yataklı oda suite",
                            Floor = (byte)3,
                            InMaintenance = false,
                            Number = (byte)1,
                            RoomType = 12
                        },
                        new
                        {
                            Id = 8,
                            Capacity = (byte)4,
                            Description = "4 kişilik çift yataklı oda",
                            Floor = (byte)3,
                            InMaintenance = false,
                            Number = (byte)2,
                            RoomType = 4
                        },
                        new
                        {
                            Id = 9,
                            Capacity = (byte)4,
                            Description = "4 kişilik çift yataklı oda",
                            Floor = (byte)3,
                            InMaintenance = false,
                            Number = (byte)3,
                            RoomType = 3
                        },
                        new
                        {
                            Id = 10,
                            Capacity = (byte)10,
                            Description = "10 kişilik çift yataklı oda",
                            Floor = (byte)4,
                            InMaintenance = false,
                            Number = (byte)1,
                            RoomType = 12
                        },
                        new
                        {
                            Id = 11,
                            Capacity = (byte)4,
                            Description = "4 kişilik çift yataklı oda",
                            Floor = (byte)4,
                            InMaintenance = false,
                            Number = (byte)2,
                            RoomType = 7
                        },
                        new
                        {
                            Id = 12,
                            Capacity = (byte)8,
                            Description = "8 kişilik çift yataklı oda",
                            Floor = (byte)4,
                            InMaintenance = false,
                            Number = (byte)3,
                            RoomType = 9
                        },
                        new
                        {
                            Id = 13,
                            Capacity = (byte)2,
                            Description = "2 kişilik çift yataklı oda",
                            Floor = (byte)5,
                            InMaintenance = false,
                            Number = (byte)1,
                            RoomType = 12
                        },
                        new
                        {
                            Id = 14,
                            Capacity = (byte)3,
                            Description = "3 kişilik çift yataklı juniorsuite oda",
                            Floor = (byte)5,
                            InMaintenance = false,
                            Number = (byte)2,
                            RoomType = 6
                        },
                        new
                        {
                            Id = 15,
                            Capacity = (byte)6,
                            Description = "6 kişilik çift yataklı kingsuite oda",
                            Floor = (byte)5,
                            InMaintenance = false,
                            Number = (byte)3,
                            RoomType = 12
                        });
                });

            modelBuilder.Entity("CustomerReservation", b =>
                {
                    b.HasOne("McSystems.DataAccess.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("McSystems.DataAccess.Entities.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Customer", b =>
                {
                    b.HasOne("McSystems.DataAccess.Entities.Country", "Country")
                        .WithMany("Customers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Reservation", b =>
                {
                    b.HasOne("McSystems.DataAccess.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("McSystems.DataAccess.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("McSystems.DataAccess.Entities.Country", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
